SET ASPNETCORE_ENVIRONMENT=Development
SET FRIENDLY_NAME=LOCAL
SET CONNECTION_STRING=Server=.\SQLEXPRESS;Database=Traducir;User Id=sa;Password=123;Min Pool Size=5;
SET STACKAPP_CLIENT_ID=18096
SET STACKAPP_KEY=nIyby7TU8iIt*0NToKhYBQ((
SET STACKAPP_SITEDOMAIN=ru.stackoverflow.com
SET
Traducir.Web
