name: build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ['Release', 'Risky']
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      shell: pwsh
      run: ./build.ps1 ${{ matrix.variant }} $env:GITHUB_RUN_NUMBER $env:GITHUB_SHA
